### ISSUE TITLE
Upgrading from VirtualBox 5.1.22 to 5.1.24 

### ISSUE THREAD

**Issue by shreddedbacon** [cppforlife/bosh-virtualbox-cpi-release#8]
I upgraded my virtualbox this morning from 5.1.22-115126~Ubuntu~xenial to  5.1.24-117012~Ubuntu~xenial and tried to build a virtualbox director and it failed with the following while building the sc instance.

Removing 5.1.24 and reinstalling 5.1.22 manually I did not encounter this error.
```
Deploying:
  Creating instance 'bosh/0':
    Creating VM:
      Creating vm with stemcell cid 'sc-516de810-92c0-4d98-7b64-6e0122704229':
        CPI 'create_vm' method responded with error: CmdError{"type":"Bosh::Clouds::CloudError","message":"Creating VM with agent ID '{{00cc5e76-a968-4162-5c01-dd9260c6b996}}': Enabling networks: Expected Host-only network 'vboxnet0' (gw 192.168.50.1 netmask 255.255.255.0) to have status 'Up'","ok_to_retry":false}

Exit code 1
```

**Comment by cppforlife** [comment]
you wouldnt have output from "vboxmanage list hostonlyifs" on the version that didnt work?

**Comment by shreddedbacon** [comment]
It said the interface existed, but the status was Down, not Up.
I could ping the IP address associated to the interface (192.168.50.1) and it responded.

I should also add that I installed the matching virtualbox extensions package when it upgraded. Before downgrading to 5.1.22, I uninstalled the 5.1.24 extensions and installed the 5.1.22 extensions and the error still existed.

If you have other output you would like to see let me know. At the moment I am not planning to upgrade again as I am using the environment. I can attempt on a machine that has never had a BOSH director built on that is running 5.1.24 later.

**Comment by ramonskie** [comment]
i have the same issues.
upgraded to 5.1.24

```
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.50.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

Name:            vboxnet1
GUID:            786f6276-656e-4174-8000-0a0027000001
DHCP:            Disabled
IPAddress:       192.168.100.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:01
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet1
```

**Comment by shreddedbacon** [comment]
Thanks @ramonskie, definitely looks to be a bug in VirtualBox.
@cppforlife I'll close this issue.
